name: Publish package to GitHub Packages
on: push
jobs:
  publish :
    runs-on: ubuntu-latest
    permissions :
      contents: read
      packages: write
    steps :
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with :
        java-version: '17'
        distribution: 'adopt'
    - name: Publish package
      run: mvn --batch-mode deploy
      env :
        GITHUS_TOKEN: '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'
